# Generated by Django 2.2 on 2020-03-26 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
