# Generated by Django 2.2 on 2020-03-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0005_auto_20200326_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(upload_to='profile_images'),
        ),
    ]
